### ISSUE TITLE
copy/paste kernels/outputs/inputs

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#1]
There's not an easy way to copy/paste kernels/outputs/inputs in the expanded view. Need to be able to see the full kernel in default mode. See image.
<img width="986" alt="Screen Shot 2019-08-30 at 11 37 52 AM" src="https://user-images.githubusercontent.com/7232183/64044014-a6d3d700-cb1a-11e9-9705-48e9142a914d.png">

**Comment by condensed-io** [comment]
I'll see what can be done to show the entire hash, we may have to go with stacking instead of a table, although I think I can make it work with the existing table

**Comment by condensed-io** [comment]
just to close out this issue, I believe all the fixes are checked in, but double check when holly has everything is up on staging...

**Comment by cgilliard** [comment]
Yes. This works now. Issue can be closed.

**Comment by hcasalet** [comment]
Chris, don't know how to close those issues. Searched the page and couldn't find how to do it. Please close the issue or let me know how to do it.

**Comment by cgilliard** [comment]
Hey Holly, there's a button below the text area that says "close issue".

**Comment by hcasalet** [comment]
Not for me.... I wonder if you have to be the one who opened the issue to be allowed to close it??

**Comment by cgilliard** [comment]
Might be a permissions issue. Let me check if you have access.

**Comment by cgilliard** [comment]
You have to accept the invitation here: https://github.com/mwcproject

Then you should be able to close out the issues.
