### ISSUE TITLE
kernels/outputs/inputs must show the block number

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#10]
See screenshot.
<img width="1158" alt="Screen Shot 2019-09-09 at 1 21 39 AM" src="https://user-images.githubusercontent.com/7232183/64504998-4a9e4f00-d2a0-11e9-8734-036483f767f2.png">

People will want to know which block the kernel/output/input were confirmed in. Info available in the servlet: https://explorer.mwc.mw/BlockExplorer?type=output&output=08cec0ba4ea5e66e5f073561cc2e91a79284b19667ccc469d9111b8ca156c3869e

**Comment by hcasalet** [comment]
<img width="1027" alt="Screen Shot 2019-11-27 at 10 39 47 PM" src="https://user-images.githubusercontent.com/47018548/69782793-e3898b80-1166-11ea-81aa-9442b7f83e54.png">
The block number should be at the top of the page, right?

**Comment by hcasalet** [comment]
Please re-open it if this issue is still there.

**Comment by cgilliard** [comment]
Yes, still an issue. The screenshot you took was of a block. Not an output. Here's an example in production: https://explorer.mwc.mw/#o08bb1fd56ae314fb819d95e336edf8b66d5c6f9b1185f007713f59bf4c4ffa0c51

**Comment by cgilliard** [comment]
Closing as "block" is actually there. I missed it somehow.
