### ISSUE TITLE
pages should be deep linkable

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#16]
If you click on "Next" from the mainpage, you cannot see the url in the browser. There should be a way to get to it.

**Comment by hcasalet** [comment]
Fixed on topic/hcasaletto/more_on_be. Will deploy it on AWS machine tomorrow.

**Comment by hcasalet** [comment]
<img width="1379" alt="Screen Shot 2019-11-28 at 11 19 09 AM" src="https://user-images.githubusercontent.com/47018548/69828538-0a7ca780-11d1-11ea-9038-f7cc51e7e9df.png">
The block number is already there. See the column to the rightmost.

**Comment by cgilliard** [comment]
I think that relates to another issue right?

**Comment by hcasalet** [comment]
Did I misunderstand it?

**Comment by cgilliard** [comment]
I think your last comment is about this issue: https://github.com/mwcproject/mwcbuildpipeline/issues/10

Right?

This issue relates to clicking the "next" button on the main page. When you do that, there's no anchor. So I can't send anyone a link to that page.

**Comment by hcasalet** [comment]
No, I fixed this deep link issue. Now there is a link. It's redeployed on
AWS. Please let me know if it looks good to you.

Thanks,
Holly

**Comment by cgilliard** [comment]
oh ok great. What's the link?

**Comment by hcasalet** [comment]
http://34.238.121.224:8080

**Comment by hcasalet** [comment]
http://34.238.121.224:8080/

**Comment by cgilliard** [comment]
Looks good. Thanks!

**Comment by cgilliard** [comment]
Just realized that if you were to email out a page for instance
http://34.238.121.224:8080/#r20, if you got the email an hour later, it
would have completely different blocks. I think we need to target off of
block height instead of last 10 or 20.

**Comment by hcasalet** [comment]
Yeah, height requires a bit more work than offset. I will change to use
height then.

Holly

**Comment by hcasalet** [comment]
Fixed and re-deployed on AWS 34.238.121.224. Please check.

Thanks,
Holly

**Comment by cgilliard** [comment]
Yes, it worked thanks!

**Comment by cgilliard** [comment]
Is there a way to make it not appear until you click the next button? I'm
thinking it makes the url look a little populated if it's always there.

**Comment by hcasalet** [comment]
Changed to not show until someone clicks next.

**Comment by cgilliard** [comment]
Awesome!
