### ISSUE TITLE
Request from @mining profit

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#18]
I need to get in response on request for each algorithm
block number
difficulty
network hashrate
the reward for the miner

**Comment by pogadaev** [comment]
hello
when do you plan to implement this functionality?

**Comment by pogadaev** [comment]
please make my application...

**Comment by cgilliard** [comment]
Sample of requested API https://api.pool.bitgrin.dev/grin/stat

**Comment by cgilliard** [comment]
completed http://explorer.mwc.mw/GHs
