### ISSUE TITLE
Verify transaction proof goes up/down three times

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#2]
<img width="547" alt="Screen Shot 2019-08-30 at 11 39 40 AM" src="https://user-images.githubusercontent.com/7232183/64044106-e995af00-cb1a-11e9-8ddc-c560022f1dba.png">

This only happens sometimes. Not sure exact details.

**Comment by cgilliard** [comment]
Proof appears not hooked up yet. See screenshot.  Error occurs when you upload a file.
<img width="998" alt="Screen Shot 2019-09-01 at 10 28 58 PM" src="https://user-images.githubusercontent.com/7232183/64092055-f7f4ee00-cd07-11e9-9979-406837008ee5.png">

**Comment by hcasalet** [comment]
Resolved.

**Comment by cgilliard** [comment]
Still saw this on the "block" pages occasionally. Maybe we can just get rid of the up/down button like you did on the home page. I don't think we need to hide it.

**Comment by hcasalet** [comment]
I don't see it. Do you see it still?

**Comment by cgilliard** [comment]
Yeah, have not noticed in a while.

**Comment by hcasalet** [comment]
Let's close it now since it is not an issue any more.
