### ISSUE TITLE
If output is spent we need to show which block it was spent in.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#21]

**Comment by hcasalet** [comment]
![Screen Shot 2019-12-04 at 12 42 34 PM](https://user-images.githubusercontent.com/47018548/70179828-a60b8d80-1693-11ea-918f-24526e795267.png)
Are we not talking about the "block" number which I highlighted in the attached screenshot?

**Comment by cgilliard** [comment]
That's where it was an output, but we need the block in which it became an
input to a new transactions.

**Comment by hcasalet** [comment]
This was added. Now we show "Spent in Block" for an output if it is spent.
