### ISSUE TITLE
block size

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#23]
There was a request for the blocksize. Need to look into how to calculate this.

**Comment by cgilliard** [comment]
The request was that the size of the block should be listed in the block explorer.

**Comment by cgilliard** [comment]
This page includes sizes: https://github.com/mimblewimble/grin/blob/master/doc/pruning.md

**Comment by hcasalet** [comment]
As a user, they probably care about how many transactions there are in a block? I don't think they necessarily care about the actual size (in terms of bytes) of a block, right?

**Comment by hcasalet** [comment]
I mean, how many outputs, inputs in a block?

**Comment by cgilliard** [comment]
There can be as little as 0 inputs and 1 output or as much as hundreds of
each.
