### ISSUE TITLE
deep linking doesn't work

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#4]
See this link: http://seed1.mwc.mw:8888/#k09062e4c9ec5a06cd40f8406e0d7ead508ed63bbb371183732fb0107099bfe7ad6

It does not display.

**Comment by cgilliard** [comment]
See example here for how it should work: https://explorer.mwc.mw/#k09062e4c9ec5a06cd40f8406e0d7ead508ed63bbb371183732fb0107099bfe7ad6

**Comment by hcasalet** [comment]
Fixed. Will deploy on seed1 soon for Chris and Brent to see.

**Comment by hcasalet** [comment]
It's now working. Please see the deployment at http://68.169.54.219:8888 

Thanks!
