### ISSUE TITLE
Kernel/output/block not found

### ISSUE THREAD

**Issue by electrum78** [mwcproject/mwcbuildpipeline#8]
When you search for a kernel/block/output that is not found it takes you to an empty page. It should not reload the page. Then you have to reload the homepage to get back to the blocks. It should not reload to this empty page when they are not found. See current block explorer behavior.

**Comment by cgilliard** [comment]
By the way accidentally created this issue from another account.

**Comment by hcasalet** [comment]
Resolved. After user acknowledges the alert message by clicking on it, the "go to All Block" link shows up and it takes them back to the all block page.
