### ISSUE TITLE
When on the first page you can still click previous taking you to an empty page

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#9]
Not sure if this is the same issue as https://github.com/mwcproject/mwcbuildpipeline/issues/7
But even if we change the styles, the user should not be able to click the button. Currently you can taking you to an empty page.

**Comment by hcasalet** [comment]
Fixed on branch "topic/hcasaletto/more_on_be" and deployed on AWS http://34.238.121.224:8080
